import 'package:flutter/material.dart';

/// Utilitaire pour les icônes - permet le tree-shaking en utilisant des icônes constantes
class IconUtils {
  IconUtils._();

  /// Liste de toutes les icônes supportées (utilisées pour créer le mapping dynamique)
  static const List<IconData> _allIcons = [
    // Icônes _rounded utilisées dans l'app
    Icons.home_rounded,
    Icons.restaurant_rounded,
    Icons.directions_car_rounded,
    Icons.shopping_bag_rounded,
    Icons.sports_esports_rounded,
    Icons.medical_services_rounded,
    Icons.school_rounded,
    Icons.savings_rounded,
    Icons.receipt_long_rounded,
    Icons.phone_android_rounded,
    Icons.flight_rounded,
    Icons.movie_rounded,
    Icons.category_rounded,
    Icons.pets_rounded,
    Icons.checkroom_rounded,
    Icons.fitness_center_rounded,
    Icons.wifi_rounded,
    Icons.lightbulb_rounded,
    Icons.account_balance_wallet_rounded,
    Icons.add_rounded,
    Icons.edit_rounded,
    Icons.delete_rounded,
    Icons.directions_bus_filled_rounded,
    Icons.home_work_rounded,
    Icons.restaurant_menu_rounded,
    Icons.more_horiz_rounded,
    
    // Icônes standard (backup)
    Icons.home,
    Icons.restaurant,
    Icons.directions_car,
    Icons.local_hospital,
    Icons.school,
    Icons.shopping_cart,
    Icons.savings,
    Icons.lightbulb,
    Icons.phone_android,
    Icons.wifi,
    Icons.sports_esports,
    Icons.movie,
    Icons.music_note,
    Icons.fitness_center,
    Icons.flight,
    Icons.beach_access,
    Icons.pets,
    Icons.child_care,
    Icons.card_giftcard,
    Icons.local_cafe,
    Icons.local_bar,
    Icons.local_grocery_store,
    Icons.local_laundry_service,
    Icons.local_pharmacy,
    Icons.call,
    Icons.credit_card,
    Icons.account_balance,
    Icons.account_balance_wallet,
    Icons.attach_money,
    Icons.trending_up,
    Icons.trending_down,
    Icons.work,
    Icons.business,
    Icons.receipt,
    Icons.shopping_bag,
    Icons.checkroom,
    Icons.laptop,
    Icons.phone_iphone,
    Icons.watch,
    Icons.directions_bus,
    Icons.train,
    Icons.local_taxi,
    Icons.local_gas_station,
    Icons.local_parking,
    Icons.build,
    Icons.cleaning_services,
    Icons.security,
    Icons.favorite,
    Icons.medical_services,
    Icons.vaccines,
    Icons.book,
    Icons.library_books,
    Icons.menu_book,
    Icons.celebration,
    Icons.people,
    Icons.family_restroom,
    Icons.cake,
    Icons.redeem,
    Icons.volunteer_activism,
    Icons.church,
    Icons.mosque,
    Icons.temple_hindu,
    Icons.self_improvement,
    Icons.spa,
    Icons.local_florist,
    Icons.palette,
    Icons.photo_camera,
    Icons.videocam,
    Icons.mic,
    Icons.headphones,
    Icons.speaker,
    Icons.tv,
    Icons.computer,
    Icons.desktop_windows,
    Icons.keyboard,
    Icons.mouse,
    Icons.memory,
    Icons.add,
    Icons.close,
    Icons.check,
    Icons.settings,
    Icons.person,
    Icons.star,
    Icons.category,
    Icons.more_horiz,
  ];

  /// Map construite dynamiquement à partir des codePoints réels
  static Map<int, IconData>? _dynamicIconMap;

  static Map<int, IconData> get _iconMap {
    _dynamicIconMap ??= {
      for (final icon in _allIcons) icon.codePoint: icon
    };
    return _dynamicIconMap!;
  }

  /// Convertit un code d'icône en IconData constant
  /// Si le code n'est pas trouvé, retourne une icône par défaut
  static IconData getIconFromCode(int code) {
    return _iconMap[code] ?? Icons.category_rounded;
  }

  /// Obtient le code d'une icône
  static int getCodeFromIcon(IconData icon) {
    return icon.codePoint;
  }

  /// Liste des icônes disponibles pour les catégories de budget
  static const List<IconData> budgetCategoryIcons = [
    Icons.home_rounded,
    Icons.restaurant_rounded,
    Icons.directions_car_rounded,
    Icons.local_hospital,
    Icons.school_rounded,
    Icons.shopping_cart,
    Icons.savings_rounded,
    Icons.lightbulb_rounded,
    Icons.phone_android_rounded,
    Icons.wifi_rounded,
    Icons.sports_esports_rounded,
    Icons.movie_rounded,
    Icons.music_note,
    Icons.fitness_center_rounded,
    Icons.flight_rounded,
    Icons.beach_access,
    Icons.pets_rounded,
    Icons.child_care,
    Icons.card_giftcard,
    Icons.local_cafe,
    Icons.local_bar,
    Icons.local_grocery_store,
    Icons.credit_card,
    Icons.account_balance,
    Icons.account_balance_wallet_rounded,
    Icons.attach_money,
    Icons.trending_up,
    Icons.work,
    Icons.business,
    Icons.receipt,
    Icons.shopping_bag_rounded,
    Icons.checkroom_rounded,
    Icons.laptop,
    Icons.phone_iphone,
    Icons.watch,
    Icons.directions_bus,
    Icons.train,
    Icons.local_taxi,
    Icons.local_gas_station,
    Icons.local_parking,
    Icons.build,
    Icons.cleaning_services,
    Icons.security,
    Icons.favorite,
    Icons.medical_services_rounded,
    Icons.book,
    Icons.library_books,
    Icons.celebration,
    Icons.people,
    Icons.family_restroom,
    Icons.cake,
    Icons.redeem,
    Icons.volunteer_activism,
    Icons.self_improvement,
    Icons.spa,
    Icons.local_florist,
    Icons.palette,
    Icons.photo_camera,
    Icons.category_rounded,
  ];

  /// Liste des icônes disponibles pour les objectifs financiers
  static const List<IconData> financialGoalIcons = [
    Icons.savings,
    Icons.home,
    Icons.directions_car,
    Icons.flight,
    Icons.beach_access,
    Icons.school,
    Icons.laptop,
    Icons.phone_iphone,
    Icons.watch,
    Icons.checkroom,
    Icons.shopping_bag,
    Icons.favorite,
    Icons.celebration,
    Icons.card_giftcard,
    Icons.account_balance,
    Icons.trending_up,
    Icons.work,
    Icons.family_restroom,
    Icons.pets,
    Icons.fitness_center,
    Icons.spa,
    Icons.local_cafe,
    Icons.restaurant,
    Icons.music_note,
    Icons.movie,
    Icons.sports_esports,
    Icons.photo_camera,
    Icons.palette,
    Icons.book,
    Icons.security,
    Icons.medical_services,
    Icons.build,
    Icons.star,
    Icons.category,
  ];
}
